---
- name: Stop certbot timer
  ansible.builtin.systemd:
    name: certbot.timer
    state: stopped
    enabled: no
  when: not nginx_letsencrypt_cert_renewal

- name: Start certbot timer
  ansible.builtin.systemd:
    name: certbot.timer
    state: started
  when: nginx_letsencrypt_cert_renewal
